trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  # Elige una versión de Python que prefieras
  displayName: 'Use Python 3.8'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install behave pytest pytest-azurepipelines
  displayName: 'Install dependencies'

- script: |
    behave
  displayName: 'Run behave tests'

- script: |
    pytest
  displayName: 'Run pytest tests'